### PR TITLE
Release.yml and text encoding improvements

### LINKED ISSUE #41: [enhancement] Automatized build, DMG and Notarization
Continuation of the discussion from #40 

TLDR: It would be great to have fully automatized build procedure with .app and .dmg sign, notarization and release.

What we have so far:

- [x] Build .app
- [x] Sign .app
- [x] Package .dmg
- [x] [Release](https://github.com/MSzturc/ThinkpadAssistant/releases/tag/v1.9.2.1) .dmg
- [x] Get commit messages since last tag and post them as a release description ( not merged currently )

Paid certificate is needed so this won't be implemented:
- [ ] Sign .dmg
- [ ] Notarize .app
- [ ] Notarize .dmg

Possibly in the future:

 [?] Generate AppCast.xml #26 

Currently untested [release.yml](https://github.com/EETagent/ThinkpadAssistant/blob/master/.github/workflows/release.yml)

Notarization is [requirement](https://developer.apple.com/news/?id=10032019a) for secure app distribution outside of ( and in ) an App Store. Without it ( Since Catalina ), user would see unknown developer warning and would have to manually allow first app launch through preferences ( Does not affect machines where is Gatekeeper disabled `sudo spctl --master-disable` ).
obrazek

### PR DESCRIPTION
**Pull request by EETagent**
partially fixes #41

### CODE REVIEW

**Comment by EETagent** [comment]
Please do not merge it currently

**Comment by EETagent** [comment]
@MSzturc Before you merge it, it is possible to have your own username instead of github-actions on published release. For that it is needed to have generated user token with repo checked, you can do that in account developer settings. After that you need to add generated hash to `MY_TOKEN` secret
Snímek obrazovky 2020-08-05 v 11 56 26
Snímek obrazovky 2020-08-05 v 11 58 37

**Comment by MSzturc** [comment]
I've generate an personal access token and added it to MY_TOKEN secret. Please add the needed code to the PR

**Comment by EETagent** [comment]
@MSzturc Added

**Pull request merged**
